### ISSUE TITLE
Azure Resource Manager Support

### ISSUE THREAD

**Issue by adnan-khalil-confiz** [fog/fog-azure#23]
The Microsoft Azure public cloud platform offers two distinct REST APIs to create and manage cloud services i.e.
- Azure Service Management (ASM) – The “old” API
- Azure Resource Manager (ARM) – The “new” API

Current fog-azure is implementing only the old API. What will be the way to go to implement the new one. My understanding is that there should be a separate provider for ARM (say fog-azurerm) as there are some overlapping functionalities in both APIs and keeping them in one provider can cause a lot of customer confusion.

What is your input on this @geemus ? @jeffmendoza and @ranjan your input will also add significant value as you people were working on this module.

**Comment by jeffmendoza** [comment]
I'd just update this one and release it as a new major version.

**Comment by shaffan-chaudhry-confiz** [comment]
What is the expected date of new version release? @jeffmendoza

**Comment by adnan-khalil-confiz** [comment]
Hey Jeff, Are you just planning to start working on it or is there something already under development? And if you are just planning to start, what will be your approach to differentiate the two APIs? Actually I need this new API integration at its earliest so was planning to develop it by myself. My concerns here are:
- Whether we should write this integration in same plugin or separate plugin for each API integration?
- If in this same plugin, what will be the approach to identify features from different APIs?
- If in the separate plugin, who will create the initial provider skeleton and what will be the contribution criteria?

**Comment by geemus** [comment]
@adnan-khalil-confiz I don't know a ton about the specifics here, but I suspect a new provider might be easiest. Probably just `fog-azure-arm` seems reasonable. That way there is less to worry about in terms of backwards compatibility and someone could actually use both while they transitioned. Does that make sense?

**Comment by jeffmendoza** [comment]
I'm not working on it, or planning to. Just sharing my 2c.

**Comment by adnan-khalil-confiz** [comment]
Moving forward on this, we have already started working on it at our end. Now @geemus will you create a separate repository in fog organization for us or we will be working in our own separate repository and will transfer it to fog after its initial releases?

**Comment by geemus** [comment]
I'm fine either way, but the easiest may be for you to just work in your own repository and we can transfer later. That way you aren't blocked on me for anything.

**Comment by adnan-khalil-confiz** [comment]
Hey @geemus we are already working on it now. Will make it public after some initial commits and documentation updates.

**Comment by geemus** [comment]
Great, thanks for the update!

**Comment by adnan-khalil-confiz** [comment]
Hey there, we have completed Major Azure Services (DNS, Compute, Network, Storage and Resource) at our end along with shindo tests. Right now we are working on minitest unit testing as it is covering the code in a much better fashion. I think its time to launch it as an open source provider here. I want you to create a new repo with name **fog-azure-rm**. Or else we can just transfer the repository. I'm not sure about the later one. What's your input on this? @geemus

**Comment by geemus** [comment]
Hey, what we have found easiest in the past is if you add me as an admin on the existing repo. That way I can just orchestrate the transfer since I would be an admin on both the repo and org (otherwise I believe it will just fail saying you have insufficient permissions if you try to transfer it in). Just transferring it that way is probably easier than trying to create and populate a new repo too. Sound good? Thanks!

**Comment by adnan-khalil-confiz** [comment]
Sounds great. I've generated a ticket to grant you admin rights. Hopefully it will take no more then 3 or 4 days. Till then, you can review the source [**here**](https://github.com/Confiz/fog-azure-rm). Develop branch is the updated one. Thinking of tagging it with initial release after completion of minitest unit tests. Also is there a checklist available for new providers? Just wanted to make sure that we are not missing anything.

**Comment by geemus** [comment]
Sounds good.

@plribeiro3000 has helped a ton with new providers lately, he may have more ideas on anything that might be missing.

**Comment by plribeiro3000** [comment]
Not sure about creating a new one. Would we have then 2 provider specific gems for the same provider under fog? Would we follow this pattern for each provider major api bump?

IMO we should just rewrite this to use the new one and bum the major version. Thats the better benefit of specific provider gems. We can bump without touching or bothering other providers. If the old one is going to be deprecated i would say just get rid of the actual implementation and use the new api, bump to a major version and we are good.

Thoughts?

**Comment by adnan-khalil-confiz** [comment]
Yes we now have 2 provider specific - azure - gems. Here we are using this pattern because Azure didn't deprecate old api. The new api is not an alternative of first api instead it is an extension of services provided by azure. Both the apis are live so we can't get rid of the old implementation. Makes sense? @plribeiro3000

**Comment by plribeiro3000** [comment]
Can't we get both together in The same gem?
The reason im saying this is because we already have tons PF provider gems
ans people claimig that they don't need all those gems. If we start
duplicating gema by provider like this is gonna be even worse.

If we allow this one to happen, why would we not allow others? IMO this
should be done inside The main azure gem. If you are saying that this is a
new API instead of a replacement so it is another reason for this to be
inside The mais gem.

How difficult would it be to push it inside The mais azure gem instead?

Em seg, 2 de mai de 2016 00:35, Adnan Khalil notifications@github.com
escreveu:

**Comment by geemus** [comment]
I don't have super strong feelings one way or the other, but keeping things in one repo might be nice. The fact that there are two fairly distinct versions is a little weird.

@adnan-khalil-confiz is this basically a superset/revision of the other interface? ie can you do everything that you could before plus more? Just trying to wrap my head around it since I'm not that familiar with azure. In particular I'm wondering how similar it might be to how things are within AWS. They never turn off old versions, but the repo just gets updated over time to use newer versions. That said, their changes also tend to be non-breaking which makes this easier (and I'm not sure that is true in the azure context).

**Comment by adnan-khalil-confiz** [comment]
Hi Geemus,

As you suggested, we have given you admin rights on our repo so that transition to fog is smooth. 
As for combining Azure Service Manager(ASM) and Azure Resource Manager(ARM) in same fog gem, we think its not a good idea because of the following reason:

ASM and ARM are essentially two different deployment models, resources created via ASM can NOT work with ARM resources and vice versa. IMO they can not co-exist in same gem. Even Microsoft ruby SDK has implemented them as separate gems ([azure-sdk-for-ruby](https://github.com/Azure/azure-sdk-for-ruby)).

Therefore, we suggest to move ahead with supporting this as a new provider.

**Comment by geemus** [comment]
Thanks for clarifying, that sounds reasonable. I'll try to get it all moved today. Could you also add me to the rubygem as an owner? That way I can manage deploys in case there are breaking changes, security issues, etc.

**Comment by geemus** [comment]
I've moved the repo and invited people as owners. Let me know if you need anything else there (and please still add me to the gem when you get a chance). Thanks!

**Comment by adnan-khalil-confiz** [comment]
Thanks for moving the repo. We have added you as rubygem owner, please add following github users as members as well

**omair-sajid-confiz**, **haider-ali-confiz**, **zeeshan-arshad-confiz**, **abbas-sheikh-confiz**

Thanks!

**Comment by geemus** [comment]
Great. They should all have invites now. Thanks!

**Comment by geemus** [comment]
Going to go ahead and close this issue since I think most everything is taken care of, just let me know if anything else comes up
